### ISSUE TITLE
Segmentation Fault / Unable to open Secondary Display

### ISSUE THREAD

**Issue by m70b1jr** [fbeltrao-br/mksts35#1]
Hey!
When I run sudo systemctl status fbcp.service , I get "unable to open secondary display. fbcp.service: Main process exited, code=exited, status=255/EXCEPTION"

running DISPLAY=:0 xlibinput_calibrator --list-devices I get "segmentation fault"

Any ideas? Thanks for doing work to get this display working!

EDIT: Turns out i forgot to install KlipperScreen, however, klipperscreen won't install either. I'm getting this error, which seems to be very recent for other people as well. How did you get around it? 

"The following packages have unmet dependencies:
 libgtk-3-0 : Depends: libwayland-client0 (>= 1.20.0) but 1.18.0-2~exp1.1 is to be installed
              Recommends: libgtk-3-bin but it is not going to be installed
E: Unable to correct problems, you have held broken packages."

EDIT: Even after installing klipperscreen, I still have the same issues as I originally did.

**Comment by Xcat2008** [comment]
i have this problem too :/

***** No bad wiring nothing! Just unnistall KlipperScreen and reinstall and should work! It's working for me now after that! 100% ! Top thanks!
**** GPIO-18 (EXP 1 / NR 3 ) need to go for 5v ! For the backlight of the LCD.

**Comment by fbeltrao-br** [comment]
This is usually caused by wrong or bad wiring.

Those Dupont cables are prone to bad contact after pulling and pushing it a few times from the GPIOs pins.

Very carefully remove the black plastic cover and bend downwards the two tabs inside the terminal to restore it clamping pressure.
