### ISSUE TITLE
Black screen after console.

### ISSUE THREAD

**Issue by Nirklav** [fbeltrao-br/mksts35#10]
Hi, first of all thank you for your guide! 

I had connected raspberry pi zero w to mks ts35 v2.
But when i worked on this i run into problem. Console with login i saw every load, but then, after 1-3 seconds, in 95% cases console was replacing by black screen, and only in 5% klipperscreen was starting as intended. 
After 2 days googling and trying all things i think i found solution. 
In that case you simply should add `hdmi_force_hotplug=1` before `hdmi_cvt=480 320 60 1`, it will be looks like this:

```
dtoverlay=disable-bt

# MKS TS35
dtparam=spi=on
hdmi_force_hotplug=1
hdmi_cvt=480 320 60 1
hdmi_group=2
hdmi_mode=87
display_hdmi_rotate=3
dtoverlay=tinylcd35,rotate=270,touch
```

Host: `raspberry pi zero w`
Os: `Raspberry Pi OS Lite, Kernel version: 6.1, Debian version: 12 (bookworm)`

**Comment by fbeltrao-br** [comment]
Raspberry Pi Zero W is under powered to run Klipperscreen and takes a considerable amount of time to load, not to tell the possible wiring fault, bad power supply or bad contact issues (Dupont connectors are very prone to this) that can lead do under voltage issues, and system updates that can suddenly break compatibility, that's why I specify with which version I tested.

I don't own a Raspberry Pi anymore to look into those issues, I switched to the Orange Pi's as they are much cheaper around here, for the price of a single 3B+ 1GB, I can buy two Orange Pi Zero 3 2GB.

**Comment by Nirklav** [comment]
It is fair, but i have Pi Zero W laying around, so i tried it. I had to say that black screen was not last problem that i met. But for now all working fine. I just want to share that problems and theris solution in actual guide.

Second problem after black screen was resolution in frame buffer 0. Raspberry don't wanted use 480x320, from this resolution was used only height, width was default, for example 1280x320. (You can read resolution from framebuffer 0 with `fbset -fb /dev/fb0` command). So i found out that minimal resolution that i can use is 720x480.

Third and last problem refers that i'm using Flyingbear ghost 6, that have vertical screen. So i need to rotate it. No metter how i tried i could not rotate it with raspberry pi settings (`display_hdmi_rotate`, `display_lcd_rotate`, `display_rotate`. `lcd_rotate`). Then i found issue where you introduced [mksts35v2.dts](https://github.com/fbeltrao-br/mksts35/blob/main/mksts35v2.dts) file. I used it to set rotation, by setting `rotate = <0x00>;`.

My final config.txt for Flyingbear ghost 6 looks like that:
```
dtoverlay=disable-bt

# MKS TS35
dtparam=spi=on
hdmi_force_hotplug=1
framebuffer_width=480
framebuffer_height=720
hdmi_group=2
hdmi_mode=87
hdmi_cvt=480 720 60 5 0 0 0
dtoverlay=mksts35v2,touch
```

I just described it here, maybe it will help somebody.
