### ISSUE TITLE
KlipperScreen does not see the screen

### ISSUE THREAD

**Issue by MaciejK98** [fbeltrao-br/mksts35#11]
![image](https://github.com/fbeltrao-br/mksts35/assets/80107067/911f1c99-5ef1-4526-866c-14b3fce3b055)
KlipperScreen returns this error, supposedly it doesn't recognize the screen but I can clearly see terminal on it.

When trying to go onward with calibration i get another message that would led me to think that theere is no display connected
![image](https://github.com/fbeltrao-br/mksts35/assets/80107067/ac546e6b-90f0-4336-b272-2e09e68ce72e)

**Comment by fbeltrao-br** [comment]
90% of the time its wiring fault. Unfortunately, I don't own a Raspberry Pi anymore to look into any issues, I switched to the Orange Pi's as they are absurdly way cheaper around here.

**Comment by MaciejK98** [comment]
So, I happened to resolve it myself, and the issue was certainly not with the wiring. I needed to add hdmi_force_hotplug=1 line to the boot.txt config file and it started working
