### ISSUE TITLE
MKS PI with TS35

### ISSUE THREAD

**Issue by faruktoy** [fbeltrao-br/mksts35#12]
Hi, have a nice day
 I have a TS35 screen that I use with Marlin, i want to change with Klipper and use the Klipperscreen. I ordered a mks pi but it doesn't have the pins you mentioned. I think the connection is made with io pins but i couldn't find any detailed information about the pins.

**Comment by fbeltrao-br** [comment]
This is only for Raspberry Pi. Device trees overlays varies by a huge margin on functionality, specially from different kernel versions depending from the used SOC in the SBC. In the case of the MKS Pi using an outdated EOL kernel with a less than ideal support for the Rockchip SOC used, I don't think it's possible to use the TS35 screen without a lot research and development. I have the MKS Pi and I just went with the Pi TFT.

**Comment by faruktoy** [comment]
I thought could use ts35, when creating an order but i was wrong. I think, can only use it as emulated st7920.

**Comment by fbeltrao-br** [comment]
You can use MKS PI-TS35 which is meant to be used with MKS PI, but not other MKS TS35 screens meant to be used with boards like Robin Nano 3.1.
