### ISSUE TITLE
MKS TS35 V2.0

### ISSUE THREAD

**Issue by xojikia** [fbeltrao-br/mksts35#2]
Hello, I did everything according to your instructions , The screen is working, it shows everything, but the touch screen is not working
![MKS TS35](https://user-images.githubusercontent.com/105436263/201028515-8ed7e480-0996-4273-958d-0452c466915c.jpg)

What is my problem?, can you help me?
Klipper / Mainsail

**Comment by fbeltrao-br** [comment]
Did you run the touchscreen calibration?

Wich raspberry pi and system image are you using?

**Comment by LashaKlipper** [comment]
Raspberry PI 3 B+ , Raspberry Pi OS using Raspberry Pi Imager
In short, I did a lot of things, it worked on one printer, but I don't know what helped :) I did so many things. I have a similar problem on the second one, the touch screen does not work, it shows everything, but the touch screen does not wor
