### ISSUE TITLE
white screen after some touch inputs

### ISSUE THREAD

**Issue by derTimm0** [fbeltrao-br/mksts35#6]
after start the display and klipperscreen work for some inputs and than the display show only a white screen. 
i use the raspiOS build from 21. feb with 5.15 kernel 

has someone a idea?

**Comment by fbeltrao-br** [comment]
Check you wiring. I've been updating this guide using multiple kernel versions and they are all working as intended. A few people have been testing this in a public Telegram community and I only update this guide after all them having their screens working without errors.
