### ISSUE TITLE
Screen rotate failure

### ISSUE THREAD

**Issue by behold81** [fbeltrao-br/mksts35#7]
I am trying to get this screen working on my PI3 running bullseye. I was using it fine on Buster but needed to upgrade for other compatibility. 

I cannot get the screen to rotate. If it use the Rotate command in the dt_overlays argument i can only get it to turn sideways and be back to front. or upsidedown (my screen can't be installed the correct way up) 

I have tried every permeable argument under the sun (least what I can find) LCD_Rotate, display_rotate ETC. but nothing. 

Any thoughts?

**Comment by fbeltrao-br** [comment]
Try this device tree:
https://github.com/fbeltrao-br/mksts35/blob/main/mksts35v2_inverted.dts

Compile:
`sudo dtc -@ -I dts -O dtb -o /boot/overlays/mksts35v2_inverted.dtbo ~/mksts35v2_inverted.dts`

And edit /boot/config.txt replacing tinylcd35 for mksts35v2_inverted.

You may need to calibrate again the touchscreen.

**Comment by behold81** [comment]
Thank you. I’ll try this tomorrow and report back.

**Comment by behold81** [comment]
That has worked Thankyou very much. need to calibrate it now.
